name: Compile LaTeX Document

on:
  push:
    branches: [ main ]  # 在推送到 main 分支时触发
  pull_request:
    branches: [ main ]  # 在针对 main 分支的 PR 时也触发

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up TeX Live
      uses: xu-cheng/texlive-action@v3
      with:
        texlive_version: 'latest'  # 使用最新版 TeX Live
        scheme: 'full'             # 完整安装以支持 XeLaTeX 和中文

    - name: Compile with XeLaTeX
      uses: xu-cheng/latex-action@v3
      with:
        latexmk_use_xelatex: true
        root_file: main.tex # 替换为你的主 LaTeX 文件名

    - name: Upload PDF artifact
      uses: actions/upload-artifact@v4
      with:
        name: main.pdf
        path: main.pdf

    - name: Create GitHub Release
      if: github.ref == 'refs/heads/main'  # 仅在推送到 main 分支时创建发布
      uses: softprops/action-gh-release@v1
      with:
        files: main.pdf
        generate_release_notes: true
