name: Compile LaTeX Document

on:
  pull_request:
    branches:
      - main
    types: 
      - closed

jobs:
  build-and-release:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository (full)
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # 获取完整的提交历史
        ref: main            # 显式指定检出 main 分支
        fetch-tags: true     # 获取所有 tags

    - name: Set up TeX Live
      uses: xu-cheng/texlive-action@v3
      with:
        texlive_version: 'latest'  # 使用最新版 TeX Live
        scheme: 'full'             # 完整安装以支持 XeLaTeX 和中文

    - name: Compile with XeLaTeX
      uses: xu-cheng/latex-action@v3
      with:
        latexmk_use_xelatex: true
        root_file: main.tex # 替换为你的主 LaTeX 文件名

    - name: Upload PDF artifact
      uses: actions/upload-artifact@v4
      with:
        name: main.pdf
        path: main.pdf

    - name: Generate release notes
      id: generate-notes
      run: |
        git fetch origin dev:dev

        # 获取最新 Release 的 Tag（如果没有则从初始提交开始）
        LATEST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "")
        
        if [ -z "$LATEST_TAG" ]; then
          # 如果是第一次发布，获取所有 dev 分支的合并提交
          COMMITS=$(git log --merges --first-parent dev --pretty=format:"- %h %s (%an)")
        else
          # 否则获取自上次 Release 后合并到 dev 的提交
          COMMITS=$(git log --merges --first-parent dev "$LATEST_TAG..HEAD" --pretty=format:"- %h %s (%an)")
        fi

        # 格式化 Release Note
        RELEASE_NOTES=$(cat <<EOF
        ### Changes since ${LATEST_TAG:-"initial commit"}

        ${COMMITS}

        _Auto-generated on $(date +'%Y-%m-%d')_
        EOF
        )

        # 输出供后续步骤使用
        echo "notes<<EOF" >> $GITHUB_OUTPUT
        echo "$RELEASE_NOTES" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: "release-$(date +'%Y.%m.%d')"
        name: "Release $(date +'%Y-%m-%d')"
        body: "${{ steps.generate-notes.outputs.notes }}"
        files: main.pdf
        draft: false
        prerelease: false
